heat_template_version: 2013-05-23

description: HOT template to deploy Marconi infrastructure

parameters:
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    description: Flavor to use for servers

resources:
  web_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: web_nodes_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          flavor: { get_param: flavor }
          image: { get_param: image }
          name: cdn_api
          user_data_format: RAW
          config_drive: "true"
          user_data: 
            Fn::Join:
              - ''
              - - |-

                  #!/bin/bash
                  export DEBIAN_FRONTEND=noninteractive

  lb:
    type: Rackspace::Cloud::LoadBalancer
    properties:
      name: cdn_lb
      nodes:
      - addresses: { get_attr: [web_nodes, accessIPv4]}
        port: 80
        condition: ENABLED
      protocol: HTTP
      port: 80
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
outputs:
  lb_public_ip:
    description: The public IP address of the load balancer
    value: { get_attr: [lb, PublicIp]}