heat_template_version: 2013-05-23

parameters:
  hostname:
    type: string
    description: Host name for DNS
  email:
    type: string
    description: Admin Email Address

resources:
  dns:
    type: "Rackspace::Cloud::DNS"
    properties:
      name: { get_param: hostname }
      emailAddress: { get_param: email }
      ttl: 301
      records:
      - name: { get_param: hostname }
        type: NS
        data: dns1.stabletransit.com
        ttl: 301
      - name: { get_param: hostname }
        type: NS
        data: dns2.stabletransit.com
        ttl: 301

      - name: { get_param: hostname }
        type: MX
        data: mx.zohomail.com
        priority: 10
        ttl: 301
      - name: { get_param: hostname }
        type: MX
        data: mx2.zohomail.com
        priority: 20
        ttl: 301
      - name: { get_param: hostname }
        type: TXT
        data: v=spf1 mx include:zoho.com ~all
        ttl: 301
      - name: { "Fn::Join" : ["", ["zb13661631.", { "Ref" : "hostname" }]] }
        type: CNAME
        data: domain.zoho.com
        ttl: 301

      - name: { get_param: hostname }
        type: A
        data: 166.78.34.26
        ttl: 301
      - name: { "Fn::Join" : ["", ["www.", { "Ref" : "hostname" }]] }
        type: CNAME
        data: { "Fn::Join" : ["", ["www.", { "Ref" : "hostname" }, ".cdn.gandhi.co.nz"]] }
        ttl: 301