heat_template_version: 2013-05-23

parameters:
  hostname:
    type: string
    description: Host name for DNS
  email:
    type: string
    description: Admin Email Address

resources:
  dns:
    type: "Rackspace::Cloud::DNS"
    properties:
      name: { get_param: hostname }
      emailAddress: { get_param: email }
      records:
      - name: { get_param: hostname }
        type: NS
        data: dns1.stabletransit.com
        ttl: 301
      - name: { get_param: hostname }
        type: NS
        data: dns2.stabletransit.com
        ttl: 301
      - name: { get_param: hostname }
        type: MX
        data: aspmx.l.google.com
        priority: 0
        ttl: 301
      - name: { get_param: hostname }
        type: MX
        data: alt1.aspmx.l.google.com
        priority: 1
        ttl: 301
      - name: { get_param: hostname }
        type: MX
        data: alt2.aspmx.l.google.com
        priority: 2
        ttl: 301
      - name: calendar
        type: CNAME
        data: ghs.google.com
        ttl: 301
      - name: docs
        type: CNAME
        data: ghs.google.com
        ttl: 301
      - name: mail
        type: CNAME
        data: ghs.google.com
        ttl: 301